import { Supplier } from '@/types'

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: '1',
    name: 'Ningbo ThermoFlask Co., Ltd.',
    source: 'Alibaba',
    url: 'https://www.alibaba.com',
    type: 'both',
    moq: 50,
    price_min: 4.20,
    price_max: 6.80,
    shipping_days_min: 12,
    shipping_days_max: 18,
    certifications: ['CE', 'RoHS', 'FDA'],
    score: 4.2,
    verified: true,
    years_on_platform: 7,
    response_rate: 94,
    description: 'Produttore specializzato in borracce termiche, vacuum flask e contenitori inox. Export verso EU e USA.',
  },
  {
    id: '2',
    name: 'Shenzhen EcoBottle Factory',
    source: 'Alibaba',
    url: 'https://www.alibaba.com',
    type: 'dropshipping',
    moq: 1,
    price_min: 5.90,
    price_max: 8.50,
    shipping_days_min: 7,
    shipping_days_max: 14,
    certifications: ['CE'],
    score: 3.7,
    verified: true,
    years_on_platform: 3,
    response_rate: 88,
    description: 'Dropshipper certificato con magazzino EU. Spedizione diretta al cliente finale, nessun minimo d\'ordine.',
  },
  {
    id: '3',
    name: 'GreenDrink Wholesale — IT',
    source: 'Web',
    url: 'https://example-supplier.it',
    type: 'stock',
    moq: 100,
    price_min: 7.50,
    price_max: 9.20,
    shipping_days_min: 2,
    shipping_days_max: 4,
    certifications: ['CE', 'BPA Free', 'ISO 9001'],
    score: 4.6,
    verified: false,
    years_on_platform: null,
    response_rate: 79,
    description: 'Grossista italiano con magazzino a Milano. Tempi di consegna rapidi, ideale per stock. Prezzi più alti ma logistica semplificata.',
  },
]
